### ISSUE TITLE
Additional metadata to better support managed cloud

### ISSUE THREAD

**Issue by mkjpryor-stfc** [cedadev/jasmin-cloud#69]
Add the ability to consume additional image metadata for:

  * Activator version
  * Additional networks

This will help us better support managed cloud use cases.

**Comment by athanasio** [comment]
`jasmin_activ_ver` : Default value `null` / empty. Acceptable values: `[0-9a-z]`, what you would expect as a SVN revision or Git commit value. Example value: '`1707`'.
`jasmin_private_if`: Default value `null` / empty. Acceptable values: `[0-9a-z]`. Example value: '`eth1`'.
